name: Test Actions locally

on: [workflow_dispatch]

jobs:
  check-pom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: GuillaumeFalourd/assert-command-line-output@v3
        with:
          command_line: cat pom.xml
          contains: JAVAVERSION

  test-for-github-workflow: # Test the action with the GitHub workflow
    needs: check-pom
    continue-on-error: true
    strategy:
      matrix:
        java: [11]
        java-distribution: [temurin]
        os: [ubuntu-latest]
        project: [maven]
    runs-on: ${{ matrix.os }}

    name: Test Java ${{ matrix.java }} ${{ matrix.java-distribution }} ${{ matrix.project }} - ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Replace string in file
        uses: MathieuSoysal/replace-string-in-file@v1.0.0
        with:
          file: pom.xml
          old-string: JAVAVERSION
          new-string: ${{ matrix.java }}

      - uses: ./ # Uses an action in the root directory
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc-test
          java-version: ${{ matrix.java }}
          target-folder: javadoc
          java-distribution: ${{ matrix.java-distribution }}
          without-deploy: true
          without-checkout: true

      - uses: GuillaumeFalourd/assert-command-line-output@v3
        with:
          command_line: cat target/pit-reports/index.html
          contains: Mutation
